name: Build & Create Archive

on:
  push:
    tags: [ 'v*.*.*' ]

env:
  TAG_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3

      - name: Install dependencies
        run: cd ./src && composer update && composer install --prefer-dist --no-suggest --no-progress

      - name: Archive Release
        uses: thedoctor0/zip-release@0.7.5
        with:
          type: 'zip'
          path: './src'
          filename: 'AuthOpenIDConnect.zip'
          exclusions: '*.git* /*node_modules/* .editorconfig'
